### ISSUE TITLE
does not work with Laravel 10

### ISSUE THREAD

**Issue by betterapp** [jackjoe/laravel-yaml-translation#1]

**Comment by jeroenbourgois** [comment]
We have not used Laravel anymore since v6 and moved to Elixir since then. I also assume nowadays there are better solutions for internationalization in Laraval?

Either way, we are happy to accept a PR.

**Comment by betterapp** [comment]
https://github.com/betterapp/laravel-yaml-translation

**Comment by jeroenbourgois** [comment]
I will then archive this project, it will be better for other users.
